# Generated by Django 2.1.4 on 2019-04-11 09:57

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=file_upload.models.user_directory_path)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
